# Generated by Django 4.1.13 on 2024-01-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=100, null=True)),
                ('type_product', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'jacket',
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=100, null=True)),
                ('type_product', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pants',
            },
        ),
        migrations.CreateModel(
            name='Sweater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=100, null=True)),
                ('type_product', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sweater',
            },
        ),
        migrations.AddField(
            model_name='shoes',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='type_product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
