# Generated by Django 4.1.13 on 2024-01-25 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(default=django.utils.timezone.now, max_length=100, unique=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('type_product', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'jackets',
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(default=django.utils.timezone.now, max_length=100, unique=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('type_product', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pants',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(default=django.utils.timezone.now, max_length=100, unique=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('type_product', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
        migrations.CreateModel(
            name='Sweaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(default=django.utils.timezone.now, max_length=100, unique=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('type_product', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sweaters',
            },
        ),
    ]
