# Generated by Django 4.1.13 on 2024-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('img', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('money', models.CharField(max_length=255)),
            ],
        ),
    ]
